name: Deploy to Azure

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the app to deploy'
        required: true
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Set up Azure CLI
        uses: azure/cli@v1.0.0
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group college-schedule-rg --name college-schedule-aks --admin

      - name: Create image pull secret for GitHub Container Registry
        run: |
          kubectl create secret docker-registry github-registry \
            --docker-server=ghcr.io \
            --docker-username=${{ github.actor }} \
            --docker-password=${{ secrets.GITHUB_TOKEN }} \
            --docker-email=${{ github.actor }}@users.noreply.github.com \
            -n default --dry-run=client -o yaml | kubectl apply -f -      - name: Deploy to Kubernetes with Helm
        run: |
          # Add Bitnami Helm repo for PostgreSQL dependency
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          
          # Deploy the application using Helm
          helm upgrade --install college-schedule ./deploy/helm \
            --set image.repository=ghcr.io/${{ github.repository }}/college-schedule-app \
            --set image.tag=${{ github.event.inputs.version }} \
            --set environment=${{ github.event.inputs.environment }} \
            --set postgresql.enabled=true \
            --set postgresql.auth.username=${{ secrets.POSTGRESQL_USERNAME || 'collegeadmin' }} \
            --set postgresql.auth.password=${{ secrets.POSTGRESQL_PASSWORD || 'college-password' }} \
            --set postgresql.auth.database=collegedb \
            --set applicationConfig.jpaDdlAuto=validate \
            --set applicationConfig.packageLogLevels."com\.college"=INFO

      - name: Health check
        run: |
          # Wait for the application to start
          sleep 30
          # Get the app URL 
          APP_URL=$(az webapp show --name college-schedule-app --resource-group college-schedule-rg --query defaultHostName -o tsv)
          # Perform a health check
          curl -f https://$APP_URL/actuator/health || exit 1

      - name: Deployment verification
        run: |
          echo "Deployment completed successfully!"
          echo "App URL: https://$(az webapp show --name college-schedule-app --resource-group college-schedule-rg --query defaultHostName -o tsv)"
