name: Deploy to Azure App Service

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the app to deploy'
        required: true
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: college-schedule-app # Замініть на назву вашого App Service
          resource-group-name: college-schedule-rg # Замініть на назву вашої групи ресурсів
          images: 'ghcr.io/${{ github.repository_owner }}/college-schedule-app:${{ github.event.inputs.version }}'
          configuration: |
            [
              {"name": "SPRING_DATASOURCE_URL", "value": "${{ secrets.SPRING_DATASOURCE_URL }}", "slotSetting": false},
              {"name": "SPRING_DATASOURCE_USERNAME", "value": "${{ secrets.POSTGRESQL_USERNAME }}", "slotSetting": false},
              {"name": "SPRING_DATASOURCE_PASSWORD", "value": "${{ secrets.POSTGRESQL_PASSWORD }}", "slotSetting": false},
              {"name": "LOGGING_LEVEL_COM_COLLEGE", "value": "${{ secrets.LOGGING_LEVEL_COM_COLLEGE || 'INFO' }}", "slotSetting": false},
              {"name": "SERVER_PORT", "value": "8080", "slotSetting": false}
            ]

      - name: Deployment verification
        run: |
          echo "Deployment completed successfully!"
          echo "App URL: https://$(az webapp show --name college-schedule-app --resource-group college-schedule-rg --query defaultHostName -o tsv)"
          
 