# Workflow для публікації пакетів Maven в GitHub Packages
# GITHUB_ACTOR та GITHUB_TOKEN автоматично надаються GitHub Actions:
# - GITHUB_ACTOR: ім'я користувача, який запустив workflow
# - GITHUB_TOKEN: автоматично генерується для кожного запуску workflow
#   і має необхідні права для публікації пакетів
name: Maven Package

# Запускається при пушах в гілку main або при створенні pull request
on:
  push:
    branches: [ "*" ]

  pull_request_target:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    # Надання необхідних дозволів для публікації пакетів
    permissions:
      contents: read
      packages: write

    steps:
    # Крок 1: Отримання коду з репозиторію
    - uses: actions/checkout@v3

    # Крок 2: Налаштування JDK 17 з кешуванням залежностей Maven
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Крок 3: Збірка проекту з Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Крок 4: Публікація артефактів в GitHub Packages
    - name: Publish to GitHub Packages from fork
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Автоматично створений токен з правами на публікацію
